package src

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
)

// === Codegen ===
//
// Codegen turns a Sema-checked *Program into C99 source text. It only
// emits code for the constructs this pass supports end-to-end: var,
// const, static var, static const, and fn (including their bodies:
// return, if/else, while, for (range and collection forms), break,
// continue, expression statements, and the expressions those bodies are
// built from).
//
// Anything Sema marked KindUnknown (struct/enum/union/generic/etc) is not
// silently miscompiled: Codegen records a clear diagnostic and skips
// emitting that construct, rather than guessing at C it can't back with a
// resolved type.
//
// Output shape mirrors the convention already established by
// utils/tinoc.h and README.md's transpile example: an `#include
// "tinoc.h"` line, followed by top-level declarations in source order.

// Codegen holds the state needed to walk a checked Program and produce C.
type Codegen struct {
	sema  *Sema
	diags *Diagnostics

	out       bytes.Buffer
	indent    int
	loopDepth int

	// inMain tracks whether the function currently being generated is
	// Tinoc's `main`, which C requires to return int even though Tinoc's
	// own signature is `fn main() void`. genReturn consults this to turn
	// a bare `return;` into `return 0;` instead of emitting an invalid
	// value-less return from an int function.
	inMain bool

	// forwardDecls collects C prototypes for every Tinoc function so
	// call order in the source doesn't have to match C's top-to-bottom
	// declare-before-use rule (Tinoc, like Sema's own signature pass,
	// allows a function to call one defined later in the file).
	forwardDecls []string

	// sourceDir is the directory of the .tnc file, used to decide whether
	// a #importc header is a local file (quote include) or a system header
	// (angle include).
	sourceDir string

	// cIncludes collects the `#include` lines demanded by #importc, and
	// cSymbolsIncluded the C function names those headers already declare
	// (so an extern "C" fn for the same symbol doesn't emit a duplicate,
	// possibly conflicting, prototype).
	cIncludes        []string
	cSymbolsIncluded map[string]bool
}

// NewCodegen constructs a Codegen bound to a Sema instance that has
// already run Check() on the program being generated, so type queries
// (TypeOf/TypeOfVarDecl/TypeOfConstDecl) return real answers.
func NewCodegen(sema *Sema, diags *Diagnostics) *Codegen {
	return &Codegen{sema: sema, diags: diags}
}

func (g *Codegen) errorAt(line, col int, format string, args ...interface{}) {
	g.diags.Error("codegen", line, col, format, args...)
}

func (g *Codegen) writeIndent() {
	g.out.WriteString(strings.Repeat("    ", g.indent))
}

func (g *Codegen) writef(format string, args ...interface{}) {
	fmt.Fprintf(&g.out, format, args...)
}

func (g *Codegen) writeln(format string, args ...interface{}) {
	g.writeIndent()
	fmt.Fprintf(&g.out, format, args...)
	g.out.WriteString("\n")
}

// Generate walks the whole program and returns the generated C source. It
// is safe to call once per Codegen instance.
func (g *Codegen) Generate(prog *Program) string {
	// Pre-pass: collect every #importc's include lines and the C symbols
	// those headers declare, before any generation starts, so extern "C"
	// prototypes can be deduped regardless of statement order.
	g.cSymbolsIncluded = make(map[string]bool)
	for _, stmt := range prog.Statements {
		if ics, ok := stmt.(*ImportCStatement); ok {
			for _, h := range ics.Headers {
				g.cIncludes = append(g.cIncludes, cIncludeDirective(h, g.sourceDir))
			}
			if mod, ok := g.sema.importCModules[ics.Alias]; ok {
				for name := range mod.Funcs {
					g.cSymbolsIncluded[name] = true
				}
			}
		}
	}

	var body bytes.Buffer

	// Emit function definitions and top-level var/const in source order
	// into `body`, while collecting forward declarations into
	// g.forwardDecls as we go, so the final output can place all
	// prototypes before any definition.
	main := &g.out
	g.out = body
	for _, stmt := range prog.Statements {
		g.genTopLevelStatement(stmt)
	}
	body = g.out
	g.out = *main

	var final bytes.Buffer
	final.WriteString("// Code generated by tinoc. DO NOT EDIT.\n")
	final.WriteString("#include \"tinoc.h\"\n")
	for _, inc := range g.cIncludes {
		final.WriteString(inc)
		final.WriteString("\n")
	}
	final.WriteString("\n")

	if len(g.forwardDecls) > 0 {
		for _, d := range g.forwardDecls {
			final.WriteString(d)
			final.WriteString(";\n")
		}
		final.WriteString("\n")
	}

	final.Write(body.Bytes())

	return final.String()
}

// genTopLevelStatement dispatches the handful of statement kinds allowed
// directly at file scope: function declarations and var/const (including
// their static forms). Anything else at top level is out of scope for
// this pass (struct/enum/union/#import/test/etc) and is reported rather
// than silently dropped.
func (g *Codegen) genTopLevelStatement(stmt Statement) {
	switch st := stmt.(type) {
	case *FunctionStatement:
		g.genFunction(st)
	case *VarStatement:
		g.genTopLevelVar(st)
	case *ConstStatement:
		g.genTopLevelConst(st)
	case *ImportStatement:
		// #import is Sema-level module resolution, not a C construct;
		// nothing to emit. (std.io's io.println etc are not yet backed
		// by a real standard library in this pass.)
	case *ImportCStatement:
		// Includes were collected in the pre-pass; nothing to emit here.
	case *ExternCFuncStatement:
		g.genExternCFuncProto(st)
	case nil:
	default:
		g.errorAt(0, 0, "codegen: unsupported top-level statement %T", stmt)
	}
}

// genExternCFuncProto emits the C prototype for an `extern "C" fn`
// declaration (unless the symbol is already declared by a #importc
// include, in which case the header's own declaration is used).
func (g *Codegen) genExternCFuncProto(ecs *ExternCFuncStatement) {
	if ecs.Name == nil || ecs.CSymbol == "" {
		return
	}
	if g.cSymbolsIncluded[ecs.CSymbol] {
		return
	}
	ret := "void"
	if ecs.ReturnType != nil {
		ret = cDeclTypeSpelling(ecs.ReturnType)
	}
	g.forwardDecls = append(g.forwardDecls, fmt.Sprintf("%s %s(%s)", ret, ecs.CSymbol, cParamListSpelling(ecs)))
}

// === Functions ===

func (g *Codegen) genFunction(fn *FunctionStatement) {
	if fn.Name == nil {
		return
	}
	if len(fn.GenericParams) > 0 {
		g.errorAt(fn.Token.Line, fn.Token.Column, "codegen: generic functions are not yet supported (%s)", fn.Name.Value)
		return
	}

	sym := g.sema.funcs[fn.Name.Value]
	if sym == nil {
		g.errorAt(fn.Token.Line, fn.Token.Column, "codegen: no resolved signature for %s (sema did not run or failed)", fn.Name.Value)
		return
	}

	retC := cReturnType(sym.ReturnType, fn.Name.Value)

	var params []string
	for i, pname := range sym.ParamNames {
		var pt *Type
		if i < len(sym.Params) {
			pt = sym.Params[i]
		}
		params = append(params, fmt.Sprintf("%s %s", cTypeOrFallback(pt), sanitizeCIdent(pname)))
	}
	if len(params) == 0 {
		params = []string{"void"}
	}
	paramList := strings.Join(params, ", ")

	cName := cFunctionName(fn.Name.Value)

	// C requires main() to return int; Tinoc's `fn main() void` maps to
	// `int main(void)` with an implicit `return 0;` appended, matching
	// the transpile example in README.md.
	isMain := fn.Name.Value == "main" && cName == "main"
	if isMain {
		retC = "int"
	}

	g.forwardDecls = append(g.forwardDecls, fmt.Sprintf("%s %s(%s)", retC, cName, paramList))

	prevInMain := g.inMain
	g.inMain = isMain

	g.writeln("%s %s(%s) {", retC, cName, paramList)
	g.indent++
	if fn.Body != nil {
		for _, st := range fn.Body.Statements {
			g.genStatement(st)
		}
	}
	if isMain && !blockAlwaysReturns(fn.Body) {
		g.writeln("return 0;")
	}
	g.indent--
	g.writeln("}")
	g.out.WriteString("\n")

	g.inMain = prevInMain
}

// cFunctionName maps a Tinoc function name to its C symbol. `main` passes
// through unchanged (it must, to be a valid C entry point); every other
// name is prefixed to avoid collisions with C standard library symbols
// (e.g. a Tinoc function literally named `printf`).
func cFunctionName(name string) string {
	if name == "main" {
		return "main"
	}
	return "tnc_" + sanitizeCIdent(name)
}

func cReturnType(t *Type, fnName string) string {
	if t == nil {
		return "void"
	}
	if t.Kind == KindUnknown {
		return "void /* unresolved return type */"
	}
	return t.CType()
}

func cTypeOrFallback(t *Type) string {
	if t == nil || t.Kind == KindInvalid {
		return "void*"
	}
	if t.Kind == KindUnknown {
		return "void*"
	}
	return t.CType()
}

// sanitizeCIdent guards against Tinoc identifiers that collide with C
// keywords (e.g. a Tinoc variable named `register` or `union`); such
// names get a suffix so the emitted C still compiles.
func sanitizeCIdent(name string) string {
	if cKeywords[name] {
		return name + "_"
	}
	return name
}

var cKeywords = map[string]bool{
	"auto": true, "break": true, "case": true, "char": true, "const": true,
	"continue": true, "default": true, "do": true, "double": true, "else": true,
	"enum": true, "extern": true, "float": true, "for": true, "goto": true,
	"if": true, "int": true, "long": true, "register": true, "return": true,
	"short": true, "signed": true, "sizeof": true, "static": true, "struct": true,
	"switch": true, "typedef": true, "union": true, "unsigned": true, "void": true,
	"volatile": true, "while": true, "inline": true, "restrict": true,
	"_Bool": true, "_Complex": true, "_Imaginary": true,
}

// === Top-level var / const ===

func (g *Codegen) genTopLevelVar(v *VarStatement) {
	t := g.sema.TypeOfVarDecl(v)
	if !g.checkEmittable(t, v.Token.Line, v.Token.Column, "var "+identName(v.Name)) {
		return
	}
	storage := "static "
	if !v.IsStatic {
		// A plain top-level `var` still needs C storage-class handling;
		// Tinoc's grammar only shows var/const inside function bodies in
		// syntax.md, but since file scope is reachable syntactically,
		// non-static top-level bindings are emitted as ordinary C globals.
		storage = ""
	}
	init := ""
	if v.Value != nil {
		init = " = " + g.genExpr(v.Value)
	} else {
		init = " = " + zeroValue(t)
	}
	g.writeln("%s%s %s%s;", storage, t.CType(), sanitizeCIdent(v.Name.Value), init)
}

func (g *Codegen) genTopLevelConst(c *ConstStatement) {
	t := g.sema.TypeOfConstDecl(c)
	if !g.checkEmittable(t, c.Token.Line, c.Token.Column, "const "+identName(c.Name)) {
		return
	}
	init := ""
	if c.Value != nil {
		init = " = " + g.genExpr(c.Value)
	}
	// `static` is applied regardless of IsStatic for top-level const,
	// since C requires internal linkage for a header-free single
	// translation unit and Tinoc const at file scope has no external
	// visibility story yet (no `pub` propagation to codegen in this pass).
	g.writeln("static const %s %s%s;", t.CType(), sanitizeCIdent(c.Name.Value), init)
}

func identName(id *Identifier) string {
	if id == nil {
		return "<anonymous>"
	}
	return id.Value
}

// checkEmittable reports (and records a diagnostic for) a nil/unresolved/
// invalid type before codegen tries to use it, so a Sema failure upstream
// turns into one clear codegen-side message instead of a nil-pointer
// panic or silently wrong C.
func (g *Codegen) checkEmittable(t *Type, line, col int, what string) bool {
	if t == nil {
		g.errorAt(line, col, "codegen: %s has no resolved type (sema error upstream)", what)
		return false
	}
	if t.Kind == KindInvalid {
		g.errorAt(line, col, "codegen: %s has an invalid type", what)
		return false
	}
	if t.Kind == KindUnknown {
		g.errorAt(line, col, "codegen: %s has an unsupported type (%s) — struct/enum/union/array/generic codegen is not implemented yet", what, t.Name)
		return false
	}
	return true
}

// zeroValue renders a type's C zero-value, used for `var x T;` (decl-only,
// no initializer) so the emitted C still gives the binding a defined
// value rather than leaving it uninitialized (Tinoc's own semantics for
// decl-only var are not yet pinned down in syntax.md, so zero-init is the
// conservative, safest default).
func zeroValue(t *Type) string {
	if t == nil {
		return "{0}"
	}
	switch t.Kind {
	case KindBool:
		return "false"
	case KindInt, KindChar:
		return "0"
	case KindFloat:
		return "0.0"
	case KindStr:
		return "tinoc_str_lit(\"\", 0)"
	case KindPointer:
		return "NULL"
	default:
		return "{0}"
	}
}

// === Statements (function-body level) ===

func (g *Codegen) genStatement(stmt Statement) {
	switch st := stmt.(type) {
	case *VarStatement:
		g.genLocalVar(st)
	case *ConstStatement:
		g.genLocalConst(st)
	case *ReturnStatement:
		g.genReturn(st)
	case *ExpressionStatement:
		if st.Expression != nil {
			g.writeln("%s;", g.genExpr(st.Expression))
		}
	case *IfStatement:
		g.genIf(st)
	case *WhileStatement:
		g.genWhile(st)
	case *ForStatement:
		g.genFor(st)
	case *BreakStatement:
		if g.loopDepth == 0 {
			g.errorAt(st.Token.Line, st.Token.Column, "codegen: break outside a loop")
			return
		}
		g.writeln("break;")
	case *ContinueStatement:
		if g.loopDepth == 0 {
			g.errorAt(st.Token.Line, st.Token.Column, "codegen: continue outside a loop")
			return
		}
		g.writeln("continue;")
	case *BlockStatement:
		g.writeln("{")
		g.indent++
		for _, s := range st.Statements {
			g.genStatement(s)
		}
		g.indent--
		g.writeln("}")
	case *ImportStatement:
		// no-op at statement level too
	case nil:
	default:
		g.errorAt(0, 0, "codegen: unsupported statement %T", stmt)
	}
}

func (g *Codegen) genLocalVar(v *VarStatement) {
	t := g.sema.TypeOfVarDecl(v)
	if !g.checkEmittable(t, v.Token.Line, v.Token.Column, "var "+identName(v.Name)) {
		return
	}
	storage := ""
	if v.IsStatic {
		storage = "static "
	}
	if v.Value != nil {
		g.writeln("%s%s %s = %s;", storage, t.CType(), sanitizeCIdent(v.Name.Value), g.genExpr(v.Value))
	} else {
		g.writeln("%s%s %s = %s;", storage, t.CType(), sanitizeCIdent(v.Name.Value), zeroValue(t))
	}
}

func (g *Codegen) genLocalConst(c *ConstStatement) {
	t := g.sema.TypeOfConstDecl(c)
	if !g.checkEmittable(t, c.Token.Line, c.Token.Column, "const "+identName(c.Name)) {
		return
	}
	storage := "const "
	if c.IsStatic {
		storage = "static const "
	}
	init := ""
	if c.Value != nil {
		init = " = " + g.genExpr(c.Value)
	}
	g.writeln("%s%s %s%s;", storage, t.CType(), sanitizeCIdent(c.Name.Value), init)
}

func (g *Codegen) genReturn(r *ReturnStatement) {
	if r.ReturnValue == nil {
		if g.inMain {
			// `fn main() void` maps to C's `int main(void)`; a bare
			// `return;` in Tinoc source becomes `return 0;` in C, since
			// C never allows a value-less return from a non-void function.
			g.writeln("return 0;")
			return
		}
		g.writeln("return;")
		return
	}
	g.writeln("return %s;", g.genExpr(r.ReturnValue))
}

func (g *Codegen) genIf(i *IfStatement) {
	cond := ""
	if i.Condition != nil {
		cond = g.genExpr(i.Condition)
	}
	g.writeln("if (%s) {", cond)
	g.indent++
	if i.Consequence != nil {
		for _, s := range i.Consequence.Statements {
			g.genStatement(s)
		}
	}
	g.indent--

	switch alt := i.Alternative.(type) {
	case nil:
		g.writeln("}")
	case *BlockStatement:
		g.writeln("} else {")
		g.indent++
		for _, s := range alt.Statements {
			g.genStatement(s)
		}
		g.indent--
		g.writeln("}")
	case *IfStatement:
		g.writeIndent()
		g.writef("} else ")
		// genElseIf writes the nested `if (...) { ... }` chain inline,
		// continuing the "} else if (...) {" C idiom instead of nesting
		// braces, which is what Tinoc's own else-if chain example expects
		// to compile down to.
		g.genElseIf(alt)
	default:
		g.writeln("}")
	}
}

// genElseIf writes an `if` statement as the continuation of an
// `} else <here>` line already started by the caller, recursing so
// `else if / else if / else` chains of any depth render as the natural C
// `} else if (...) { ... } else if (...) { ... } else { ... }` shape
// rather than deeply nested blocks.
func (g *Codegen) genElseIf(i *IfStatement) {
	cond := ""
	if i.Condition != nil {
		cond = g.genExpr(i.Condition)
	}
	g.writef("if (%s) {\n", cond)
	g.indent++
	if i.Consequence != nil {
		for _, s := range i.Consequence.Statements {
			g.genStatement(s)
		}
	}
	g.indent--

	switch alt := i.Alternative.(type) {
	case nil:
		g.writeln("}")
	case *BlockStatement:
		g.writeln("} else {")
		g.indent++
		for _, s := range alt.Statements {
			g.genStatement(s)
		}
		g.indent--
		g.writeln("}")
	case *IfStatement:
		g.writeIndent()
		g.writef("} else ")
		g.genElseIf(alt)
	default:
		g.writeln("}")
	}
}

func (g *Codegen) genWhile(w *WhileStatement) {
	cond := "true"
	if w.Condition != nil {
		cond = g.genExpr(w.Condition)
	}
	g.writeln("while (%s) {", cond)
	g.indent++
	g.loopDepth++
	if w.Body != nil {
		for _, s := range w.Body.Statements {
			g.genStatement(s)
		}
	}
	g.loopDepth--
	g.indent--
	g.writeln("}")
}

// genFor lowers both of Tinoc's for-loop forms to C `for`:
//
//	for <start>..<end> |i| { ... }   -> for (i32 i = start; i < end; i++) { ... }
//	for <collection> |x| { ... }     -> for (size_t <idx> = 0; <idx> < <coll>.len; <idx>++) { T x = <coll>.ptr[<idx>]; ... }
//
// The collection form assumes a slice/array-with-.len-and-.ptr shape,
// matching the slice representation documented in syntax.md; since
// array/slice types aren't resolved by Sema yet in this pass, the
// collection form is accepted syntactically but flagged as unsupported
// until array/slice codegen lands, rather than emitting code that likely
// won't compile.
func (g *Codegen) genFor(f *ForStatement) {
	if f.Collection != nil {
		g.errorAt(f.Token.Line, f.Token.Column, "codegen: for-over-collection is not yet supported (array/slice types aren't resolved yet)")
		return
	}

	capture := "_i"
	if f.Capture != nil {
		capture = sanitizeCIdent(f.Capture.Value)
	}
	start := "0"
	if f.Start != nil {
		start = g.genExpr(f.Start)
	}
	end := "0"
	if f.End != nil {
		end = g.genExpr(f.End)
	}

	g.writeln("for (i32 %s = %s; %s < %s; %s++) {", capture, start, capture, end, capture)
	g.indent++
	g.loopDepth++
	if f.Body != nil {
		for _, s := range f.Body.Statements {
			g.genStatement(s)
		}
	}
	g.loopDepth--
	g.indent--
	g.writeln("}")
}

// === Expressions ===
//
// genExpr renders an expression to a C source fragment. It leans on
// Sema's resolved types (via g.sema.TypeOf) where the distinction matters
// for correct C (e.g. picking str-vs-numeric formatting), but for this
// pass's scope (var/const/fn) most expressions translate near
// syntactically, since Tinoc's expression grammar is deliberately
// C-like.

func (g *Codegen) genExpr(e Expression) string {
	switch ex := e.(type) {
	case *Identifier:
		return sanitizeCIdent(ex.Value)
	case *IntegerLiteral:
		return genIntegerLiteral(ex)
	case *FloatLiteral:
		return ex.Raw
	case *StringLiteral:
		// Unescape once, then re-emit C-escaped: the raw Tinoc text is
		// already C-valid, but %q-style double escaping would print a
		// literal \n; emitting raw risks breaking on embedded \" quotes.
		// The length passed to tinoc_str_lit is the unescaped byte count.
		u := unescapeCString(ex.Value)
		return fmt.Sprintf("tinoc_str_lit(%s, %d)", cQuote(u), len(u))
	case *CharLiteral:
		return genCharLiteral(ex)
	case *BoolLiteral:
		if ex.Value {
			return "true"
		}
		return "false"
	case *NullLiteral:
		return "NULL"
	case *PrefixExpression:
		return g.genPrefix(ex)
	case *PostfixExpression:
		return g.genPostfix(ex)
	case *InfixExpression:
		return g.genInfix(ex)
	case *AssignExpression:
		return g.genAssign(ex)
	case *CallExpression:
		return g.genCall(ex)
	case *IndexExpression:
		left := ""
		if ex.Left != nil {
			left = g.genExpr(ex.Left)
		}
		idx := ""
		if ex.Index != nil {
			idx = g.genExpr(ex.Index)
		}
		return fmt.Sprintf("%s[%s]", left, idx)
	case *FieldAccessExpression:
		// #importc member access: cio.EOF / cio.stdin resolve to the C
		// name itself, since the emitted #include declares it.
		if mod, ok := g.sema.moduleAlias(ex.Left); ok && ex.Field != nil {
			if c, ok := mod.Consts[ex.Field.Value]; ok {
				return c.CSymbol
			}
		}
		left := ""
		if ex.Left != nil {
			left = g.genExpr(ex.Left)
		}
		field := ""
		if ex.Field != nil {
			field = ex.Field.Value
		}
		return fmt.Sprintf("%s.%s", left, field)
	case *ArrayLiteral:
		var parts []string
		for _, el := range ex.Elements {
			parts = append(parts, g.genExpr(el))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	default:
		g.errorAt(0, 0, "codegen: unsupported expression %T", e)
		return "/* unsupported expression */ 0"
	}
}

// genIntegerLiteral re-emits an integer literal's original base/notation
// (decimal, 0x, 0o -> converted to C's 0 octal form, 0b -> converted since
// C99 has no binary literal syntax) with underscores stripped, since C
// doesn't allow underscore digit separators.
func genIntegerLiteral(lit *IntegerLiteral) string {
	raw := strings.ReplaceAll(lit.Raw, "_", "")
	switch {
	case strings.HasPrefix(raw, "0x") || strings.HasPrefix(raw, "0X"):
		return raw // C99 hex literal syntax matches Tinoc's directly
	case strings.HasPrefix(raw, "0b") || strings.HasPrefix(raw, "0B"):
		// C99 has no binary literal syntax; emit the pre-computed decimal
		// value instead (Value was parsed from the same literal in the
		// parser).
		return fmt.Sprintf("%d", lit.Value)
	case strings.HasPrefix(raw, "0o") || strings.HasPrefix(raw, "0O"):
		return "0" + raw[2:] // C octal literals are a bare leading 0
	default:
		return raw
	}
}

func genCharLiteral(cl *CharLiteral) string {
	// Tinoc's char is a Unicode codepoint (u32 underneath, see syntax.md);
	// single ASCII-range char literals map directly to a C char constant,
	// which is sufficient for this pass's scope.
	u := unescapeCString(cl.Value)
	if len(u) == 1 {
		q := cQuote(u)
		return "'" + q[1:len(q)-1] + "'"
	}
	return "'" + cl.Value + "'"
}

// unescapeCString resolves the C-style escape sequences Tinoc's lexer
// keeps verbatim (\n, \t, \", \\, \xHH, ...) into the actual bytes.
// Unknown escapes pass through as backslash + char.
func unescapeCString(raw string) string {
	var b strings.Builder
	for i := 0; i < len(raw); i++ {
		c := raw[i]
		if c != '\\' || i+1 >= len(raw) {
			b.WriteByte(c)
			continue
		}
		i++
		switch raw[i] {
		case 'n':
			b.WriteByte('\n')
		case 't':
			b.WriteByte('\t')
		case 'r':
			b.WriteByte('\r')
		case '0':
			b.WriteByte(0)
		case 'a':
			b.WriteByte('\a')
		case 'b':
			b.WriteByte('\b')
		case 'f':
			b.WriteByte('\f')
		case 'v':
			b.WriteByte('\v')
		case '\\':
			b.WriteByte('\\')
		case '\'':
			b.WriteByte('\'')
		case '"':
			b.WriteByte('"')
		case 'x':
			if i+1 < len(raw) && isHexDigit(raw[i+1]) {
				hi := hexVal(raw[i+1])
				i++
				if i+1 < len(raw) && isHexDigit(raw[i+1]) {
					b.WriteByte(byte(hi*16 + hexVal(raw[i+1])))
					i++
				} else {
					b.WriteByte(byte(hi))
				}
			} else {
				b.WriteString("\\x")
			}
		default:
			b.WriteByte('\\')
			b.WriteByte(raw[i])
		}
	}
	return b.String()
}

func hexVal(c byte) int {
	switch {
	case c >= '0' && c <= '9':
		return int(c - '0')
	case c >= 'a' && c <= 'f':
		return int(c-'a') + 10
	case c >= 'A' && c <= 'F':
		return int(c-'A') + 10
	default:
		return 0
	}
}

// cQuote renders a byte string as a C string literal, escaping only the
// characters C requires. Non-ASCII bytes pass through raw (preserving
// UTF-8) rather than being turned into \uXXXX.
func cQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\t':
			b.WriteString("\\t")
		case '\r':
			b.WriteString("\\r")
		case 0:
			b.WriteString("\\0")
		case '\a':
			b.WriteString("\\a")
		case '\b':
			b.WriteString("\\b")
		case '\f':
			b.WriteString("\\f")
		case '\v':
			b.WriteString("\\v")
		default:
			b.WriteByte(s[i])
		}
	}
	b.WriteByte('"')
	return b.String()
}

func (g *Codegen) genPrefix(pe *PrefixExpression) string {
	right := ""
	if pe.Right != nil {
		right = g.genExpr(pe.Right)
	}
	switch pe.Operator {
	case "-":
		return "(-" + right + ")"
	case "!":
		return "(!" + right + ")"
	case "~":
		return "(~" + right + ")"
	case "&":
		return "(&" + right + ")"
	case "-%":
		return "(-" + right + ")" // wrapping negation: C's signed overflow on unsigned types already wraps
	default:
		g.errorAt(pe.Token.Line, pe.Token.Column, "codegen: unsupported prefix operator %q", pe.Operator)
		return right
	}
}

func (g *Codegen) genPostfix(pe *PostfixExpression) string {
	left := ""
	if pe.Left != nil {
		left = g.genExpr(pe.Left)
	}
	switch pe.Operator {
	case "^": // pointer dereference
		return "(*" + left + ")"
	case "?": // optional unwrap — not yet backed by real optional codegen
		g.errorAt(pe.Token.Line, pe.Token.Column, "codegen: optional unwrap is not yet supported")
		return left
	default:
		g.errorAt(pe.Token.Line, pe.Token.Column, "codegen: unsupported postfix operator %q", pe.Operator)
		return left
	}
}

// cInfixOp maps Tinoc infix operators to their C spelling. Most pass
// through unchanged since Tinoc's core arithmetic/comparison/bitwise
// operators are deliberately C-shaped; `and`/`or` are the two that need
// translation to `&&`/`||`.
func cInfixOp(op string) (string, bool) {
	switch op {
	case "and":
		return "&&", true
	case "or":
		return "||", true
	case "+", "-", "*", "/", "%", "==", "!=", "<", ">", "<=", ">=", "&", "|", "^", "<<", ">>":
		return op, true
	default:
		return "", false
	}
}

func (g *Codegen) genInfix(ie *InfixExpression) string {
	left := ""
	if ie.Left != nil {
		left = g.genExpr(ie.Left)
	}
	right := ""
	if ie.Right != nil {
		right = g.genExpr(ie.Right)
	}

	if cop, ok := cInfixOp(ie.Operator); ok {
		return fmt.Sprintf("(%s %s %s)", left, cop, right)
	}

	switch ie.Operator {
	case "+%", "-%", "*%":
		// Wrapping arithmetic: tinoc.h provides tinoc_wrap_add/sub/mul
		// macros that cast through the operand's own type, matching C's
		// well-defined unsigned wraparound semantics.
		fn := map[string]string{"+%": "tinoc_wrap_add", "-%": "tinoc_wrap_sub", "*%": "tinoc_wrap_mul"}[ie.Operator]
		return fmt.Sprintf("%s(%s, %s)", fn, left, right)
	default:
		g.errorAt(ie.Token.Line, ie.Token.Column, "codegen: unsupported operator %q", ie.Operator)
		return fmt.Sprintf("(%s /* unsupported op %s */ %s)", left, ie.Operator, right)
	}
}

func (g *Codegen) genAssign(ae *AssignExpression) string {
	target := ""
	if ae.Target != nil {
		target = g.genExpr(ae.Target)
	}
	value := ""
	if ae.Value != nil {
		value = g.genExpr(ae.Value)
	}

	switch ae.Operator {
	case "=", "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=":
		return fmt.Sprintf("(%s %s %s)", target, ae.Operator, value)
	default:
		g.errorAt(ae.Token.Line, ae.Token.Column, "codegen: unsupported assignment operator %q", ae.Operator)
		return fmt.Sprintf("(%s = %s)", target, value)
	}
}

func (g *Codegen) genCall(ce *CallExpression) string {
	// #importc module call: cio.printf(...) -> printf(...), with str
	// arguments unwrapped to their data pointer (Tinoc's str is a struct;
	// C's printf wants a const char *).
	if fa, ok := ce.Function.(*FieldAccessExpression); ok {
		if mod, isMod := g.sema.moduleAlias(fa.Left); isMod && fa.Field != nil {
			if fn, ok := mod.Funcs[fa.Field.Value]; ok {
				return g.genCCall(fn.CSymbol, ce)
			}
		}
		g.errorAt(ce.Token.Line, ce.Token.Column, "codegen: unsupported call target (module/method calls are not yet implemented)")
		return "/* unsupported call */ 0"
	}

	ident, isIdent := ce.Function.(*Identifier)
	if !isIdent {
		g.errorAt(ce.Token.Line, ce.Token.Column, "codegen: unsupported call target (module/method calls are not yet implemented)")
		return "/* unsupported call */ 0"
	}
	if len(ce.GenericArgs) > 0 {
		g.errorAt(ce.Token.Line, ce.Token.Column, "codegen: generic calls are not yet supported (%s)", ident.Value)
	}

	// extern "C" fn: printf(...) -> printf(...) under its real C symbol.
	if sym, ok := g.sema.externCFuncs[ident.Value]; ok {
		return g.genCCall(sym.CSymbol, ce)
	}

	var args []string
	for _, a := range ce.Arguments {
		args = append(args, g.genExpr(a))
	}
	return fmt.Sprintf("%s(%s)", cFunctionName(ident.Value), strings.Join(args, ", "))
}

// genCCall renders a call to a real C function (extern "C" fn or #importc
// member), unwrapping str arguments to their data pointer and emitting
// bare string literals directly.
func (g *Codegen) genCCall(cName string, ce *CallExpression) string {
	var args []string
	for _, a := range ce.Arguments {
		args = append(args, g.genCArg(a))
	}
	return fmt.Sprintf("%s(%s)", cName, strings.Join(args, ", "))
}

// genCArg renders one argument of a real C call. A string literal becomes
// a plain C string literal (no tinoc_str_lit wrapper), and any str-typed
// expression Sema flagged for unwrapping passes its data pointer.
func (g *Codegen) genCArg(a Expression) string {
	if sl, ok := a.(*StringLiteral); ok {
		return cQuote(unescapeCString(sl.Value))
	}
	if g.sema.cStrArgs[a] {
		return "(" + g.genExpr(a) + ").data"
	}
	return g.genExpr(a)
}

// === CLI Entry Point ===

// GenerateC runs the full front end (parse -> sema -> codegen) over
// source text and returns the generated C source alongside every
// diagnostic collected along the way. If any error-severity diagnostic
// was recorded at any stage, the returned C string is empty: partial/
// best-effort C for a program with real errors would be misleading to
// hand to a C compiler.
func GenerateC(file, source string) (string, *Diagnostics) {
	prog, sema, diags := RunSema(file, source)
	if diags.HasErrors() {
		return "", diags
	}

	gen := NewCodegen(sema, diags)
	gen.sourceDir = filepath.Dir(file)
	code := gen.Generate(prog)

	if diags.HasErrors() {
		return "", diags
	}
	return code, diags
}
