package src

import "core:fmt"
import "core:strings"

// Codegen lowers the scoped AST (variables, constants, basic functions)
// into C source text. It leans on utils/tinoc.h for the primitive type
// typedefs (i32, u8, str, ...) so the emitted C stays close to what a
// human would hand-write against that header.

Codegen :: struct {
	sb:     strings.Builder,
	indent: int,
}

codegen_make :: proc() -> Codegen {
	return Codegen{sb = strings.builder_make(), indent = 0}
}

cg_write :: proc(cg: ^Codegen, s: string) {
	strings.write_string(&cg.sb, s)
}

cg_writef :: proc(cg: ^Codegen, fmt_str: string, args: ..any) {
	s := fmt.tprintf(fmt_str, ..args)
	strings.write_string(&cg.sb, s)
}

cg_indent :: proc(cg: ^Codegen) {
	for i := 0; i < cg.indent; i += 1 {
		strings.write_string(&cg.sb, "    ")
	}
}

// c_type_name maps a Tinoc primitive type name to its tinoc.h C typedef.
// Types outside this scoped subset pass through unchanged (best-effort);
// semantics should have already flagged anything truly unknown.
c_type_name :: proc(tinoc_type: string) -> string {
	switch tinoc_type {
	case "void": return "void"
	case "bool": return "bool"
	case "char": return "char32"
	case "str": return "str"
	case "i8", "i16", "i32", "i64", "i128", "isize",
	     "u8", "u16", "u32", "u64", "u128", "usize",
	     "f32", "f64", "f128":
		return tinoc_type
	}
	return tinoc_type
}

// generate_c transpiles a checked Program into a complete C source file.
generate_c :: proc(program: ^Program) -> string {
	cg := codegen_make()

	cg_write(&cg, "// Generated by tinoc — do not edit by hand.\n")
	cg_write(&cg, "#include \"tinoc.h\"\n\n")

	for fn in program.functions {
		gen_fn_decl(&cg, fn)
		cg_write(&cg, "\n")
	}

	return strings.to_string(cg.sb)
}

gen_fn_decl :: proc(cg: ^Codegen, fn: ^Fn_Decl) {
	cg_writef(cg, "%s %s(", c_type_name(fn.return_type.name), fn.name)

	if len(fn.params) == 0 {
		cg_write(cg, "void")
	} else {
		for param, i in fn.params {
			if i > 0 {
				cg_write(cg, ", ")
			}
			cg_writef(cg, "%s %s", c_type_name(param.type_expr.name), param.name)
		}
	}
	cg_write(cg, ") ")

	gen_block(cg, fn.body)
}

gen_block :: proc(cg: ^Codegen, block: ^Block_Stmt) {
	cg_write(cg, "{\n")
	cg.indent += 1
	for stmt in block.statements {
		gen_stmt(cg, stmt)
	}
	cg.indent -= 1
	cg_indent(cg)
	cg_write(cg, "}\n")
}

gen_stmt :: proc(cg: ^Codegen, stmt: Stmt) {
	switch v in stmt {
	case ^Var_Decl_Stmt:
		gen_var_decl(cg, v)
	case ^Const_Decl_Stmt:
		gen_const_decl(cg, v)
	case ^Return_Stmt:
		gen_return_stmt(cg, v)
	case ^Expr_Stmt:
		cg_indent(cg)
		gen_expr(cg, v.expr)
		cg_write(cg, ";\n")
	case ^Assign_Stmt:
		gen_assign_stmt(cg, v)
	case ^If_Stmt:
		gen_if_stmt(cg, v)
	case ^Block_Stmt:
		cg_indent(cg)
		gen_block(cg, v)
	}
}

// resolved_type_name picks the C type to declare a var/const with: the
// explicit annotation if present, otherwise a best-effort guess from the
// initializer (semantics has already validated consistency by this point).
resolved_var_type :: proc(type_expr: Maybe(Type_Expr), init: Maybe(Expr)) -> string {
	if te, ok := type_expr.?; ok {
		return c_type_name(te.name)
	}
	if init_expr, ok := init.?; ok {
		return c_type_name(guess_type_name_from_expr(init_expr))
	}
	return "i32" // last-resort fallback; semantics requires type or init
}

// guess_type_name_from_expr mirrors semantics' literal-inference rules
// closely enough to pick a reasonable default C type for `var x = expr;`.
guess_type_name_from_expr :: proc(e: Expr) -> string {
	switch v in e {
	case ^Int_Lit_Expr: return "i32"
	case ^Float_Lit_Expr: return "f64"
	case ^String_Lit_Expr: return "str"
	case ^Char_Lit_Expr: return "char"
	case ^Bool_Lit_Expr: return "bool"
	case ^Ident_Expr: return "i32"
	case ^Binary_Expr: return guess_type_name_from_expr(v.left)
	case ^Unary_Expr: return guess_type_name_from_expr(v.operand)
	case ^Call_Expr: return "i32"
	case ^Paren_Expr: return guess_type_name_from_expr(v.inner)
	}
	return "i32"
}

gen_var_decl :: proc(cg: ^Codegen, decl: ^Var_Decl_Stmt) {
	cg_indent(cg)
	type_name := resolved_var_type(decl.type_expr, decl.init)
	cg_writef(cg, "%s %s", type_name, decl.name)
	if init_expr, has_init := decl.init.?; has_init {
		cg_write(cg, " = ")
		gen_expr(cg, init_expr)
	} else {
		cg_write(cg, " = {0}")
	}
	cg_write(cg, ";\n")
}

gen_const_decl :: proc(cg: ^Codegen, decl: ^Const_Decl_Stmt) {
	cg_indent(cg)
	type_name := resolved_var_type(decl.type_expr, decl.init)
	cg_writef(cg, "const %s %s", type_name, decl.name)
	if init_expr, has_init := decl.init.?; has_init {
		cg_write(cg, " = ")
		gen_expr(cg, init_expr)
	}
	cg_write(cg, ";\n")
}

gen_return_stmt :: proc(cg: ^Codegen, stmt: ^Return_Stmt) {
	cg_indent(cg)
	cg_write(cg, "return")
	if value, has_value := stmt.value.?; has_value {
		cg_write(cg, " ")
		gen_expr(cg, value)
	}
	cg_write(cg, ";\n")
}

gen_assign_stmt :: proc(cg: ^Codegen, stmt: ^Assign_Stmt) {
	cg_indent(cg)
	op_str := "="
	switch stmt.op {
	case .Assign: op_str = "="
	case .Add_Assign: op_str = "+="
	case .Sub_Assign: op_str = "-="
	case .Mul_Assign: op_str = "*="
	case .Div_Assign: op_str = "/="
	case .Mod_Assign: op_str = "%="
	}
	cg_writef(cg, "%s %s ", stmt.name, op_str)
	gen_expr(cg, stmt.value)
	cg_write(cg, ";\n")
}

gen_if_stmt :: proc(cg: ^Codegen, stmt: ^If_Stmt) {
	cg_indent(cg)
	cg_write(cg, "if (")
	gen_expr(cg, stmt.cond)
	cg_write(cg, ") ")
	gen_block(cg, stmt.then_body)

	if else_body, has_else := stmt.else_body.?; has_else {
		// Undo the trailing newline+closing-brace indentation so `else`
		// lands on the same line as the closing `}` of the then-branch.
		text := strings.to_string(cg.sb)
		if strings.has_suffix(text, "}\n") {
			strings.pop_byte(&cg.sb) // remove '\n'
			strings.pop_byte(&cg.sb) // remove '}'
			cg_write(cg, "} else ")
		} else {
			cg_indent(cg)
			cg_write(cg, "else ")
		}
		gen_block(cg, else_body)
	}
}

gen_expr :: proc(cg: ^Codegen, e: Expr) {
	switch v in e {
	case ^Ident_Expr:
		cg_write(cg, v.name)
	case ^Int_Lit_Expr:
		cg_write(cg, v.text)
	case ^Float_Lit_Expr:
		cg_write(cg, v.text)
	case ^String_Lit_Expr:
		gen_string_lit(cg, v.value)
	case ^Char_Lit_Expr:
		gen_char_lit(cg, v.value)
	case ^Bool_Lit_Expr:
		cg_write(cg, v.value ? "true" : "false")
	case ^Binary_Expr:
		gen_expr(cg, v.left)
		cg_writef(cg, " %s ", binary_op_c_str(v.op))
		gen_expr(cg, v.right)
	case ^Unary_Expr:
		cg_write(cg, unary_op_c_str(v.op))
		gen_expr(cg, v.operand)
	case ^Call_Expr:
		cg_writef(cg, "%s(", v.callee)
		for arg, i in v.args {
			if i > 0 {
				cg_write(cg, ", ")
			}
			gen_expr(cg, arg)
		}
		cg_write(cg, ")")
	case ^Paren_Expr:
		cg_write(cg, "(")
		gen_expr(cg, v.inner)
		cg_write(cg, ")")
	}
}

// gen_string_lit emits a Tinoc `str` literal using the tinoc_str_lit
// helper from tinoc.h, so the result carries a length alongside the
// pointer rather than relying on NUL-termination.
gen_string_lit :: proc(cg: ^Codegen, value: string) {
	escaped := c_escape_string(value)
	cg_writef(cg, "tinoc_str_lit(\"%s\", %d)", escaped, len(value))
}

gen_char_lit :: proc(cg: ^Codegen, value: string) {
	if len(value) == 0 {
		cg_write(cg, "0")
		return
	}
	escaped := c_escape_char(value)
	cg_writef(cg, "'%s'", escaped)
}

c_escape_string :: proc(s: string) -> string {
	sb := strings.builder_make()
	for i := 0; i < len(s); i += 1 {
		ch := s[i]
		switch ch {
		case '"':
			strings.write_string(&sb, "\\\"")
		case '\\':
			strings.write_string(&sb, "\\\\")
		case '\n':
			strings.write_string(&sb, "\\n")
		case '\t':
			strings.write_string(&sb, "\\t")
		case '\r':
			strings.write_string(&sb, "\\r")
		case:
			strings.write_byte(&sb, ch)
		}
	}
	return strings.to_string(sb)
}

c_escape_char :: proc(s: string) -> string {
	ch := s[0]
	switch ch {
	case '\'':
		return "\\'"
	case '\\':
		return "\\\\"
	case '\n':
		return "\\n"
	case '\t':
		return "\\t"
	case '\r':
		return "\\r"
	}
	return s
}

binary_op_c_str :: proc(op: Binary_Op) -> string {
	switch op {
	case .Add: return "+"
	case .Sub: return "-"
	case .Mul: return "*"
	case .Div: return "/"
	case .Mod: return "%"
	case .Eq: return "=="
	case .Not_Eq: return "!="
	case .Less: return "<"
	case .Less_Eq: return "<="
	case .Greater: return ">"
	case .Greater_Eq: return ">="
	case .And: return "&&"
	case .Or: return "||"
	}
	return "?"
}

unary_op_c_str :: proc(op: Unary_Op) -> string {
	switch op {
	case .Neg: return "-"
	case .Not: return "!"
	}
	return "?"
}
